name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # ðŸ”¥ Added packages for your project
  http: ^1.2.2
  web_socket_channel: ^3.0.1

  # Optional (recommended for clean models)
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # For generating model classes
  build_runner: ^2.4.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
